name: bitewise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  provider: ^6.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
    
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logo/

