name: bitewise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_ai: ^2.0.0
  flutter_dotenv: ^5.2.1
  fl_chart: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
    
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logo/
    - assets/meals/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/bitewise_logo_1024-512x512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21