name: Deploy iOS to TestFlight

on:
  push:
    tags:
      - 'v*'       # Örn: v1.0.0 gibi versiyon tag'leriyle tetiklenir
    branches:
      - main       # veya sadece main'e push olduğunda çalışır

jobs:
  ios_build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: stable
          cache: true
        id: flutter
      
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.4"
          bundler-cache: true
          working-directory: ios

      - name: Build and Deploy to TestFlight
        env: 
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_JSON_KEY: ${{ secrets.ASC_JSON_KEY }}
          MATCH_GIT_BASIC_AUTHARIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHARIZATION }}
        run: |
          cd ./ios 
          bundle exec fastlane ios beta